### ISSUE TITLE
Fatal error: Call to undefined function normalizer_normalize()

### ISSUE THREAD

**Issue by ncarboni** [PhilippMundhenk/Kirby-Table-of-Contents#1]
Hi,
I have a problem with this kirby extension. It runs smoothly on my computer with MAMP. No problem there, but if I try to put it on a server it gives me this error:

```
Fatal error: Call to undefined function normalizer_normalize() in /membri/dilljob/site/tags/sections.php on line 51
```

I tried with on two different servers, the first one (Altervista) gives me the above error, the other (local Apache + PHP5.4) it doesn't load anything in page from the moment I use the extension (so, no problem with header and title of the page, but the rest it is simply not there)

Any idea/suggestions?

**Comment by PhilippMundhenk** [comment]
It might be that the required **intl** extension is not enabled on the servers where it is not working: http://stackoverflow.com/questions/8949663/php-5-3-cant-find-normalizer-normalize
Thus, the normalize function is not found. You might have to enable that extension manually or ask your hoster to do so. The link above gives you some pointers.
It is available in most modern hosters which is why I decided to go with it. But apparently this is not the case everywhere.

Some background: The normalize functions is necessary here to get rid of special characters, such as spaces in the link to the specific section, as a link to such a text with such characters would fail.

**Comment by ncarboni** [comment]
Thanks, as soon as I have a second I try to install it, see if it is working and in case close the issue :+1:

**Comment by PhilippMundhenk** [comment]
I just pushed an update, getting rid of the normalizer. As the call to normalizer is no longer included, I will close this issue. It should run on your server now.
